kind: pipeline
name: default

steps:
- name: docker-dovecot
  image: plugins/docker
  settings:
    dockerfile: dovecot/Dockerfile
    repo: tlemarchand/dovecot
    tags:
      - latest
      - build-${DRONE_BUILD_NUMBER}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password